/*++
Copyright (c) 2006 Microsoft Corporation

Module Name:

    id_gen.h

Abstract:

    Basic support for generating & recycling ids.

Author:

    Leonardo de Moura (leonardo) 2008-02-02.

Revision History:

--*/
#pragma once

#include "util/vector.h"
#include "util/util.h"

// If SmallestFirst=true, ID generation is deterministic regardless of
// recycling order.
template<bool SmallestFirst>
class id_gen_tpl {
    unsigned        m_next_id;
    // Min-heap (smallest ID at the front) if SmallestFirst, otherwise a stack.
    unsigned_vector m_free_ids;
public:
    id_gen_tpl(unsigned start = 0):m_next_id(start) {}
    
    unsigned mk() {
        unsigned r;
        if (m_free_ids.empty()) {
            r = m_next_id;
            m_next_id++;
        }
        else {
            if constexpr (SmallestFirst)
                std::pop_heap(m_free_ids.begin(), m_free_ids.end(), std::greater<unsigned>());
            r = m_free_ids.back();
            m_free_ids.pop_back();
        }
        return r;
    }
    
    void recycle(unsigned id) { 
        if (memory::is_out_of_memory())
            return;
        m_free_ids.push_back(id);
        if constexpr (SmallestFirst)
            std::push_heap(m_free_ids.begin(), m_free_ids.end(), std::greater<unsigned>());
    }
    
    void reset(unsigned start = 0) {
        m_next_id = start;
        m_free_ids.reset();
    }

    void cleanup(unsigned start = 0) {
        m_next_id = start;
        m_free_ids.finalize();
    }
    
    unsigned show_hash() {
        unsigned_vector ids(m_free_ids);
        if constexpr (SmallestFirst)
            std::sort(ids.begin(), ids.end());
        unsigned h = string_hash(std::string_view(reinterpret_cast<char const*>(ids.data()), ids.size()*sizeof(unsigned)), 17);
        return hash_u_u(h, m_next_id);
    }

    /**
       \brief Return N if the range of ids generated by this module is in the set [0..N)
    */
    unsigned get_id_range() const { return m_next_id; }


    /**
       \brief Debugging support method: set m_next_id to the least value id' s.t. id' >= id and id' is not in m_free_ids.
       This method is only used to create small repros that exposes bugs in Z3.
    */
    unsigned set_next_id(unsigned id) {
        m_next_id = id;
        while (std::find(m_free_ids.begin(), m_free_ids.end(), m_next_id) != m_free_ids.end())
            m_next_id++;
        return m_next_id;
    }

    void display_free_ids(std::ostream & out) {
        unsigned_vector ids(m_free_ids);
        if constexpr (SmallestFirst)
            std::sort(ids.begin(), ids.end());
        ::display(out, ids.begin(), ids.end());
    }

};

// Preserve LIFO recycling for clients that do not need a canonical order.
using id_gen = id_gen_tpl<false>;

// Choose the smallest free ID, independently of the order of completed releases.
// Only the free set at the next allocation matters; heap layout is not observable.
using ordered_id_gen = id_gen_tpl<true>;
