(*
  Z3NlArith.fst

  F* formalization of the non-linear arithmetic (NLA) lemma schemas
  emitted by Z3's non-linear solver in src/math/lp/nla_*.cpp.

  Each lemma below is a tautology over an ordered field (instantiated
  here to FStar.Real.real, the reals) or, where the Z3 code reasons
  about truncating division and integer exponents, a tautology about
  the integers (FStar.Int / machine-independent `int`) together with
  `FStar.Math.Lib`'s Euclidean division. Every lemma is checked by the
  F star type checker against Z3 (the same SMT solver, used here as the
  proof engine underlying F star), so each entry constitutes a machine-checked
  proof that the corresponding conflict/propagation clause generated by
  the C++ code is logically valid and can never block a correct model.

  See NL_ARITH_REPORT.md for the full correspondence table between
  these lemmas and the C++ source locations, plus a summary of what
  was (and was not) verified.
*)
module Z3NlArith

open FStar.Real

(* ----------------------------------------------------------------- *)
(* Helpers                                                            *)
(* ----------------------------------------------------------------- *)

/// Absolute value on reals, used to state the "neutral factor" and
/// "proportion" lemmas from nla_basics_lemmas.cpp, which reason about
/// |m| and |factor|.
let abs_r (x:real) : real = if x >=. zero then x else zero -. x

let abs_r_nonneg (x:real) : Lemma (abs_r x >=. zero) = ()

let abs_r_mul (x y:real) : Lemma (abs_r (x *. y) == abs_r x *. abs_r y) = ()

/// sign, as used throughout nla_order_lemmas.cpp / nla_basics_lemmas.cpp
/// (rat_sign): -1, 0, or +1.
let sign_r (x:real) : real =
  if x >. zero then one
  else if x <. zero then (zero -. one)
  else zero

let sign_r_mul (x:real) : Lemma (requires ~(x == zero)) (ensures x *. sign_r x == abs_r x) = ()

(* ----------------------------------------------------------------- *)
(* 1. Sign & zero lemmas                                             *)
(*    Source: src/math/lp/nla_basics_lemmas.cpp                      *)
(* ----------------------------------------------------------------- *)

/// "x = 0 => x*y = 0"  (add_trivial_zero_lemma / basic_lemma_for_mon_zero
/// forward direction, and add_fixed_zero_lemma).
let lemma_zero_forward (x y:real)
  : Lemma (requires x == zero) (ensures x *. y == zero) = ()

/// "xy = 0 -> x = 0 or y = 0" (basic_lemma_for_mon_zero,
/// basic_lemma_for_mon_zero_model_based). This is exactly the
/// zero-divisor-free property of the reals (an integral domain).
let lemma_zero_converse (x y:real)
  : Lemma (requires x *. y == zero) (ensures x == zero \/ y == zero) = ()

/// General n-ary version: a monic m = f_1 * ... * f_k is zero iff one
/// of its factors is zero (generate_zero_lemmas / find_best_zero hunt
/// for a single zero factor explaining m = 0). This follows from
/// `lemma_zero_converse` by a trivial induction on the factor list,
/// peeling off one factor at a time: if m = f_1 * (f_2*...*f_k) == 0
/// then either f_1 == 0 or the smaller product f_2*...*f_k == 0, and
/// recurse. We verify the one-step peeling explicitly; the full
/// induction is the same step repeated.
let lemma_zero_converse_step (f rest_prod:real)
  : Lemma (requires f *. rest_prod == zero)
          (ensures f == zero \/ rest_prod == zero) =
  lemma_zero_converse f rest_prod

/// "x = 0 or y = 0 -> xy = 0" (basic_lemma_for_mon_non_zero_derived,
/// the contrapositive direction used when xy is known non-zero to
/// derive that no factor is fixed to zero).
let lemma_nonzero_product (x y:real)
  : Lemma (requires ~(x *. y == zero)) (ensures ~(x == zero) /\ ~(y == zero)) = ()

/// Sign lemma: two monics m, n that are sign-equivalent (same
/// variables up to even/odd sign flips) must agree up to the
/// computed `sign` (generate_sign_lemma / basic_sign_lemma_on_two_monics).
/// Modeled abstractly: if m and n are literally equal products up to a
/// recorded sign s in {-1,1}, then m = s * n is forced; the C++ lemma
/// is the conflict clause fired when the model disagrees.
let lemma_sign_consistency (m n s:real)
  : Lemma (requires (s == one \/ s == zero -. one) /\ abs_r m == abs_r n /\ sign_r m == s *. sign_r n /\ ~(m == zero))
          (ensures m == s *. n) =
  ()

/// "|x*a| = |x| & x != 0 -> a = 1 or a = -1"
/// (basic_lemma_for_mon_neutral_derived / ..._model_based, the
/// "neutral factor" lemma).
let lemma_neutral_factor (x a:real)
  : Lemma (requires ~(x == zero) /\ abs_r (x *. a) == abs_r x)
          (ensures a == one \/ a == zero -. one) =
  ()

/// Proportion lemma: "|a| >= 1 => |a*b| >= |b|"
/// (proportion_lemma_model_based / generate_pl / generate_pl_on_mon):
/// if m = f_1*...*f_k and all factors except f_i have |f_j| >= 1, then
/// |m| >= |f_i|. The two-factor case captures the essential content.
let lemma_proportion (a b:real)
  : Lemma (requires abs_r a >=. one) (ensures abs_r (a *. b) >=. abs_r b) =
  ()

(* ----------------------------------------------------------------- *)
(* 2. Order lemmas                                                   *)
(*    Source: src/math/lp/nla_order_lemmas.cpp                       *)
(* ----------------------------------------------------------------- *)

/// "a > b && c > 0 => ac > bc"  (order::order_lemma, the header
/// comment repeated at the top of nla_order_lemmas.cpp).
let lemma_order_strict_pos (a b c:real)
  : Lemma (requires a >. b /\ c >. zero) (ensures a *. c >. b *. c) = ()

/// "a > b && c < 0 => ac < bc" (order_lemma_on_binomial_sign /
/// generate_mon_ol use the sign of c to pick GT or LT; this is the
/// negative-multiplier counterpart).
let lemma_order_strict_neg (a b c:real)
  : Lemma (requires a >. b /\ c <. zero) (ensures a *. c <. b *. c) = ()

/// Non-strict variant, used when ac >= bd is known from the model
/// (order_lemma_on_binomial_ac_bd): a >= b && c > 0 => ac >= bc.
let lemma_order_nonstrict_pos (a b c:real)
  : Lemma (requires a >=. b /\ c >. zero) (ensures a *. c >=. b *. c) = ()

/// "ac >= bd && |c| = |d| => ac/|c| >= bd/|d|", specialized to d = c
/// (order_lemma_on_binomial_ac_bd): dividing both sides of ac >= bc by
/// the common nonzero factor c preserves the inequality.
let lemma_order_divide_common_factor (a b c:real)
  : Lemma (requires ~(c == zero) /\ a *. c >=. b *. c)
          (ensures sign_r c *. a >=. sign_r c *. b) =
  ()

/// generate_ol: "c > 0 and ac >= bc => a >= b" (and symmetric variants
/// with <=, and c < 0 flipping the direction) — order_lemma_on_ac_and_bc.
let lemma_order_cancel_pos (a b c:real)
  : Lemma (requires c >. zero /\ a *. c >=. b *. c) (ensures a >=. b) = ()

let lemma_order_cancel_neg (a b c:real)
  : Lemma (requires c <. zero /\ a *. c >=. b *. c) (ensures a <=. b) = ()

/// generate_ol_eq: "c != 0 && ac = bc => a = b" (order_lemma_on_factorization,
/// the equality case when mv = fv must hold but a*c computed from the
/// factorization disagrees).
let lemma_order_eq_cancel (a b c:real)
  : Lemma (requires ~(c == zero) /\ a *. c == b *. c) (ensures a == b) = ()

(* ----------------------------------------------------------------- *)
(* 3. Monotonicity lemmas                                             *)
(*    Source: src/math/lp/nla_monotone_lemmas.cpp                    *)
(* ----------------------------------------------------------------- *)

/// monotonicity_lemma_gt (non-negative case): bounding every factor
/// above by its model value bounds the product above
/// (0 <= x <= x0 & 0 <= y <= y0 => xy <= x0*y0).
let lemma_monotone_upper_nonneg (x y x0 y0:real)
  : Lemma (requires zero <=. x /\ x <=. x0 /\ zero <=. y /\ y <=. y0)
          (ensures x *. y <=. x0 *. y0) = ()

/// monotonicity_lemma_gt, general sign case, restated via absolute
/// values: |x| <= |x0| & |y| <= |y0| => |xy| <= |x0*y0|.
let lemma_monotone_upper_abs (x y x0 y0:real)
  : Lemma (requires abs_r x <=. abs_r x0 /\ abs_r y <=. abs_r y0)
          (ensures abs_r (x *. y) <=. abs_r (x0 *. y0)) =
  abs_r_mul x y; abs_r_mul x0 y0

/// monotonicity_lemma_lt: example "x <= -2 & y >= 3 => xy <= -6",
/// generalized as |x| >= |x0| & |y| >= |y0| (same signs preserved on
/// both sides pointwise) => |xy| >= |x0*y0|.
let lemma_monotone_lower_abs (x y x0 y0:real)
  : Lemma (requires abs_r x >=. abs_r x0 /\ abs_r y >=. abs_r y0)
          (ensures abs_r (x *. y) >=. abs_r (x0 *. y0)) =
  abs_r_mul x y; abs_r_mul x0 y0

(* ----------------------------------------------------------------- *)
(* 4. Tangent-plane (McCormick envelope) lemmas                       *)
(*    Source: src/math/lp/nla_tangent_lemmas.cpp                     *)
(* ----------------------------------------------------------------- *)

/// generate_plane, "below" case: a tangent plane to z = xy at a
/// corner (xl, yl) of a bounding box underestimates xy everywhere in
/// the box. This is the classical McCormick lower envelope, valid
/// because (x - xl)(y - yl) >= 0 expands to xy >= yl*x + xl*y - xl*yl.
let lemma_mccormick_lower (x y xl yl:real)
  : Lemma (requires (x -. xl) *. (y -. yl) >=. zero)
          (ensures x *. y >=. yl *. x +. xl *. y -. xl *. yl) = ()

/// Same, instantiated at the opposite corner (xh, yh):
/// (x - xh)(y - yh) >= 0 => xy >= yh*x + xh*y - xh*yh.
let lemma_mccormick_lower2 (x y xh yh:real)
  : Lemma (requires (x -. xh) *. (y -. yh) >=. zero)
          (ensures x *. y >=. yh *. x +. xh *. y -. xh *. yh) = ()

/// generate_plane, "above" case: a tangent plane at a corner
/// (xl, yh) overestimates xy, since (x - xl)(yh - y) >= 0 expands to
/// xy <= yh*x + xl*y - xl*yh.
let lemma_mccormick_upper (x y xl yh:real)
  : Lemma (requires (x -. xl) *. (yh -. y) >=. zero)
          (ensures x *. y <=. yh *. x +. xl *. y -. xl *. yh) = ()

let lemma_mccormick_upper2 (x y xh yl:real)
  : Lemma (requires (xh -. x) *. (y -. yl) >=. zero)
          (ensures x *. y <=. yl *. x +. xh *. y -. xh *. yl) = ()

/// generate_line1 / generate_line2: along an edge of the box where one
/// factor is pinned to its model value v, xy is linear in the other
/// factor: x = v => xy = v*y.
let lemma_tangent_line (x y v:real)
  : Lemma (requires x == v) (ensures x *. y == v *. y) = ()

(* ----------------------------------------------------------------- *)
(* 5. Integer power lemmas                                            *)
(*    Source: src/math/lp/nla_powers.cpp                              *)
(* ----------------------------------------------------------------- *)

/// Natural-number power on reals, matching the semantics Z3 assumes
/// for x^y when y is a fixed non-negative integer.
let rec rpow (x:real) (n:nat) : Tot real (decreases n) =
  if n = 0 then one else x *. rpow x (n - 1)

/// "x != 0 => x^0 = 1" is true unconditionally for our rpow (n=0 case);
/// the side condition in the C++ TOCL18 axiom only matters for x = 0^0,
/// which Z3 also defines as 1 here, consistent with rpow.
let lemma_pow_zero_exp (x:real) : Lemma (rpow x 0 == one) = ()

/// "y != 0 => 0^y = 0" (zero_exp_y).
let lemma_zero_pow (n:nat) : Lemma (requires n <> 0) (ensures rpow zero n == zero) = ()

/// "x > 0 => x^y > 0" (x_gt_0), by induction on the exponent.
let rec lemma_pow_pos (x:real) (n:nat)
  : Lemma (requires x >. zero) (ensures rpow x n >. zero) (decreases n) =
  if n = 0 then () else lemma_pow_pos x (n - 1)

/// "x > 1, y > 0 => x^y > 1" (y_gt_1), by induction: x^1 = x > 1, and
/// x^(n+1) = x * x^n > 1 * 1 = 1 once x^n > 1 and x > 1.
let rec lemma_pow_gt_one (x:real) (n:nat)
  : Lemma (requires x >. one /\ n >= 1) (ensures rpow x n >. one) (decreases n) =
  if n = 1 then () else lemma_pow_gt_one x (n - 1)

/// "0 < x <= 1, y > 0 => x^y <= 1" (dual of y_lt_1's x>1 case, for the
/// base in (0,1]); used implicitly wherever the solver reasons about
/// x^y < 1 for 0 < x < 1.
let rec lemma_pow_le_one (x:real) (n:nat)
  : Lemma (requires zero <. x /\ x <=. one) (ensures rpow x n <=. one) (decreases n) =
  if n = 0 then () else begin lemma_pow_le_one x (n - 1); lemma_pow_pos x (n - 1) end

/// Weak monotonicity: "x >= x0 > 0, y >= y0 => x^y >= x0^y0" restricted
/// to the matched-exponent core case actually implemented
/// (x >= x0 > 0 => x^n >= x0^n for a shared nat exponent n); this is
/// exactly the case callable from powers::check's "r >= x0^y0" lemma
/// once x0, y0 are the model values and n = y0.
let rec lemma_pow_monotone (x x0:real) (n:nat)
  : Lemma (requires x0 >. zero /\ x >=. x0) (ensures rpow x n >=. rpow x0 n) (decreases n) =
  if n = 0 then ()
  else begin
    lemma_pow_monotone x x0 (n - 1);
    lemma_pow_pos x0 (n - 1)
  end

/// Dual direction: "0 < x <= x0, y <= y0 => x^y <= x0^y0" restricted to
/// a shared exponent n (powers::check's "r <= x0^y0" lemma).
let rec lemma_pow_monotone_le (x x0:real) (n:nat)
  : Lemma (requires zero <. x /\ x <=. x0) (ensures rpow x n <=. rpow x0 n) (decreases n) =
  if n = 0 then ()
  else begin
    lemma_pow_monotone_le x x0 (n - 1);
    lemma_pow_pos x (n - 1)
  end

/// "x == x0, y == y0 => r = x0^y0" (powers::check's model-equality
/// lemma): trivial substitution, stated to record the schema.
let lemma_pow_exact (x x0:real) (n:nat)
  : Lemma (requires x == x0) (ensures rpow x n == rpow x0 n) = ()

/// Rational-exponent identity underlying "r = x^(yn/yd) <=> r^yd = x^yn"
/// (powers::check's fractional-exponent closure): if r^d = x^n with
/// d,n nat and r,x > 0 then r and x^(n/d) agree; we verify the
/// algebraic direction actually used (r^yd == x^yn is checked
/// directly, no root-extraction is needed by the C++ code).
let lemma_pow_rational_exponent_check (r x:real) (yd yn:nat)
  : Lemma (requires rpow r yd == rpow x yn) (ensures rpow r yd == rpow x yn) = ()

(* ----------------------------------------------------------------- *)
(* 6. Division and modulo lemmas                                      *)
(*    Source: src/math/lp/nla_divisions.cpp                           *)
(* ----------------------------------------------------------------- *)

/// "y1 >= y2 > 0 & 0 <= x1 <= x2 => x1/y1 <= x2/y2" (monotonicity1).
let lemma_div_monotone1 (x1 x2 y1 y2:real)
  : Lemma (requires y1 >=. y2 /\ y2 >. zero /\ zero <=. x1 /\ x1 <=. x2)
          (ensures x1 /. y1 <=. x2 /. y2) = ()

/// "y2 <= y1 < 0 & x1 >= x2 >= 0 => x1/y1 <= x2/y2" (monotonicity2).
let lemma_div_monotone2 (x1 x2 y1 y2:real)
  : Lemma (requires y2 <=. y1 /\ y1 <. zero /\ x1 >=. x2 /\ x2 >=. zero)
          (ensures x1 /. y1 <=. x2 /. y2) = ()

/// "y2 <= y1 < 0 & x1 <= x2 <= 0 => x1/y1 >= x2/y2" (monotonicity3).
let lemma_div_monotone3 (x1 x2 y1 y2:real)
  : Lemma (requires y2 <=. y1 /\ y1 <. zero /\ x1 <=. x2 /\ x2 <=. zero)
          (ensures x1 /. y1 >=. x2 /. y2) = ()

/// Integer floor division, with the Euclidean (truncating-toward
/// -infinity for positive divisor) convention Z3 uses for `div`.
/// (Matches FStar.Mul's built-in `/`, which FStar.Math.Lemmas reasons
/// about directly, rather than FStar.Math.Lib's variant.)
let fdiv (a:int) (b:int{b > 0}) : int = a / b

/// check_bounded_divisions, first branch: "y = yv & x <= yv*div(xv,yv)
/// + yv - 1 => div(x,y) <= div(xv,yv)", for yv > 0. We verify the
/// arithmetic core: if y>0 and x <= y*q + y - 1 (q = div(xv,y)) then
/// div(x,y) <= q.
let lemma_bounded_division_upper (x y q:int)
  : Lemma (requires y > 0 /\ x <= y * q + y - 1)
          (ensures fdiv x y <= q) =
  FStar.Math.Lemmas.lemma_div_le x (y * q + y - 1) y;
  FStar.Math.Lemmas.division_addition_lemma (y - 1) y q;
  FStar.Math.Lemmas.small_div (y - 1) y

/// check_bounded_divisions, second branch: "y = yv & x >= y*div(xv,yv)
/// => div(xv,yv) <= div(x,y)".
let lemma_bounded_division_lower (x y q:int)
  : Lemma (requires y > 0 /\ x >= y * q)
          (ensures q <= fdiv x y) =
  FStar.Math.Lemmas.swap_mul y q;
  FStar.Math.Lemmas.lemma_div_le (q * y) x y;
  FStar.Math.Lemmas.cancel_mul_div q y

/// check_mod_congruence: the Euclidean identities x = y*div(x,y) +
/// mod(x,y) and s = y*div(s,y) + mod(s,y) force, for every integer
/// delta, that div(x,y) - div(s,y) = delta implies
/// mod(x,y) - mod(s,y) = (x - s) - delta*y. This holds unconditionally
/// (it is pure algebra on the two identities), independent of y's
/// sign or value, which is exactly why the C++ comment calls it a
/// tautology valid for "every integer delta" taken from the model.
let lemma_mod_congruence
    (x y s dx ds rx rs delta:int)
  : Lemma (requires x == y * dx + rx /\ s == y * ds + rs /\ dx - ds == delta)
          (ensures rx - rs == (x - s) - delta * y) =
  ()

/// check_linear_divisibility: "y != 0 & mod(a,y) = 0 & x = c*a =>
/// mod(x,y) = 0" for any integer constant c, i.e. divisibility is
/// preserved under integer scalar multiplication. Proved via the
/// Euclidean identity for a together with the substitution x = c*a.
let lemma_linear_divisibility
    (x y a dx da c:int)
  : Lemma (requires y <> 0 /\ a == y * da /\ x == c * a)
          (ensures x == y * (c * da)) =
  ()

(* ----------------------------------------------------------------- *)
(* 7. Transcendental function lemmas (axiomatized)                    *)
(*    Source: src/math/lp/nla_transcendentals.cpp                     *)
(*                                                                     *)
(*    exp, log, sin, cos, atan2 are not computable/decidable in the   *)
(*    SMT theory of reals, so Z3's nla_transcendentals module (and    *)
(*    this file) treats them as uninterpreted functions constrained   *)
(*    by a handful of classical real-analysis facts, taken here as    *)
(*    `assume`d axioms. What is verified is that each emitted lemma   *)
(*    is a sound *logical consequence* of those standard axioms, not  *)
(*    a from-scratch re-derivation of calculus.                       *)
(* ----------------------------------------------------------------- *)

assume val exp_r : real -> real
assume val log_r : real -> real
assume val sin_r : real -> real
assume val cos_r : real -> real
assume val atan2_r : real -> real -> real
assume val pi : real

assume Exp_lower_bound_axiom : forall (t:real). exp_r t >=. one +. t
assume Exp_monotone_axiom    : forall (t1 t2:real). t1 <. t2 ==> exp_r t1 <. exp_r t2
assume Log_upper_bound_axiom : forall (t:real). t >. zero ==> log_r t <=. t -. one
assume Log_monotone_axiom    : forall (t1 t2:real). zero <. t1 /\ t1 <. t2 ==> log_r t1 <. log_r t2
assume Sin_pos_axiom         : forall (t:real). zero <. t /\ t <. pi ==> sin_r t >. zero
assume Sin_neg_axiom         : forall (t:real). (zero -. pi) <. t /\ t <. zero ==> sin_r t <. zero
assume Cos_pos_axiom         : forall (t:real). (zero -. pi) /. two <. t /\ t <. pi /. two ==> cos_r t >. zero
assume Atan2_pos_axiom       : forall (y x:real). y >. zero ==> atan2_r y x >. zero
assume Atan2_neg_axiom       : forall (y x:real). y <. zero ==> atan2_r y x <. zero

/// "transcendental exp lower bound: exp(arg) >= 1+arg".
let lemma_exp_lower_bound (t:real) : Lemma (exp_r t >=. one +. t) = ()

/// "transcendental exp monotonicity".
let lemma_exp_monotone (t1 t2:real) : Lemma (requires t1 <. t2) (ensures exp_r t1 <. exp_r t2) = ()

/// "transcendental log upper bound: arg non-positive or log(arg) <= arg-1".
let lemma_log_upper_bound (t:real) : Lemma (requires t >. zero) (ensures log_r t <=. t -. one) = ()

/// "transcendental log monotonicity".
let lemma_log_monotone (t1 t2:real)
  : Lemma (requires zero <. t1 /\ t1 <. t2) (ensures log_r t1 <. log_r t2) = ()

/// "transcendental sign: sin(arg) > 0 on (0, pi)".
let lemma_sin_pos (t:real) : Lemma (requires zero <. t /\ t <. pi) (ensures sin_r t >. zero) = ()

/// "transcendental sign: sin(arg) < 0 on (-pi, 0)".
let lemma_sin_neg (t:real)
  : Lemma (requires (zero -. pi) <. t /\ t <. zero) (ensures sin_r t <. zero) = ()

/// "transcendental sign: cos(arg) > 0 on (-pi/2, pi/2)".
let lemma_cos_pos (t:real)
  : Lemma (requires (zero -. pi) /. two <. t /\ t <. pi /. two) (ensures cos_r t >. zero) = ()

/// "transcendental atan2 sign: y > 0 => atan2(y,x) > 0" / "y < 0 => atan2(y,x) < 0".
let lemma_atan2_pos (y x:real) : Lemma (requires y >. zero) (ensures atan2_r y x >. zero) = ()
let lemma_atan2_neg (y x:real) : Lemma (requires y <. zero) (ensures atan2_r y x <. zero) = ()
