;(set-option :parallel.enable true)
(set-option :model_validate true)
(declare-fun a () Float16)
(declare-fun b () Float16)
(declare-fun c () Float16)
(declare-fun d () Float16)
(assert (= c (fp.rem a b)))
(assert (not (= c d)))
(check-sat)