# Release pipeline
# * Builds for all platforms (with code signing)
# * Creates packages for Python and NuGet
# * Uploads build products to stores (GitHub, NuGet, PyPI)

trigger: none

stages:

# Builds Z3 on various platforms
- stage: Build
  jobs:

  - job: MacBuild
    displayName: "Mac Build"
    pool:
      vmImage: "macOS-10.14"
    steps:
    - script: python scripts/mk_unix_dist.py --dotnet-key=$(Build.SourcesDirectory)/resources/z3.snk
    - script: git clone https://github.com/z3prover/z3test z3test
    - script: python z3test/scripts/test_benchmarks.py build-dist/z3 z3test/regressions/smt2
    - script: cp dist/*.zip $(Build.ArtifactStagingDirectory)/.
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'Mac'
        targetPath: $(Build.ArtifactStagingDirectory)

  - job: UbuntuBuild
    displayName: "Ubuntu build"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - script: python scripts/mk_unix_dist.py --dotnet-key=$(Build.SourcesDirectory)/resources/z3.snk
    - script: git clone https://github.com/z3prover/z3test z3test
    - script: python z3test/scripts/test_benchmarks.py build-dist/z3 z3test/regressions/smt2
    - script: cp dist/*.zip $(Build.ArtifactStagingDirectory)/.
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'Ubuntu'
        targetPath: $(Build.ArtifactStagingDirectory)

  - job: ManylinuxBuild
    displayName: "Manylinux build"
    pool:
      vmImage: "ubuntu-16.04"
    container: "rhelmot/manylinux1_x86_64:latest"
    variables:
      python: "/opt/python/cp35-cp35m/bin/python"
    steps:
    - script: $(python) scripts/mk_unix_dist.py --nodotnet --nojava
    - script: git clone https://github.com/z3prover/z3test z3test
    - script: $(python) z3test/scripts/test_benchmarks.py build-dist/z3 z3test/regressions/smt2
    - script: cp dist/*.zip $(Build.ArtifactStagingDirectory)/
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'Manylinux'
        targetPath: $(Build.ArtifactStagingDirectory)
  
  - job: WindowsBuild32
    displayName: "Windows build (32-bit)"
    pool:
      vmImage: "vs2017-win2016"
    steps:
    - task: CmdLine@2
      inputs:
        script:
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars32.bat" &&
          python scripts\mk_win_dist.py
              --x86-only
              --dotnet-key=$(Build.SourcesDirectory)/resources/z3.snk
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: dist
        artifactName: 'Windows32'

  - job: WindowsBuild64
    displayName: "Windows build (64-bit)"
    pool:
      vmImage: "vs2017-win2016"
    steps:
    - task: CmdLine@2
      inputs:
        script:
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&
          python scripts\mk_win_dist.py
              --x64-only
              --dotnet-key=$(Build.SourcesDirectory)/resources/z3.snk
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: dist
        artifactName: 'Windows64'

- stage: Sign
  jobs:

  - job: SignWindows32Assemblies
    displayName: "Sign 32-bit Windows Assemblies"
    pool:
      vmImage: "windows-latest"
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: c6e283d3-5018-4982-b28f-8a88c50174e2
        pipeline: 7
        runVersion: specific
        runId: 47
        artifact: 'Windows32'
        path: $(Build.ArtifactStagingDirectory)
    - task: EsrpCodeSigning@1
      inputs:
        ConnectedServiceName: 'z3-esrp-signing'
        FolderPath: '$(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x86-win/bin'
        Pattern: 'Microsoft.Z3.dll,libz3.dll,libz3java.dll,z3.exe'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [
            {
              "keyCode": "CP-230012",
              "operationSetCode": "SigntoolSign",
              "parameters": [
                {
                  "parameterName": "OpusName",
                  "parameterValue": "Microsoft"
                },
                {
                  "parameterName": "OpusInfo",
                  "parameterValue": "http://www.microsoft.com"
                },
                {
                  "parameterName": "PageHash",
                  "parameterValue": "/NPH"
                },
                {
                  "parameterName": "FileDigest",
                  "parameterValue": "/fd sha256"
                },
                {
                  "parameterName": "TimeStamp",
                  "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                }
              ],
              "toolName": "signtool.exe",
              "toolVersion": "6.2.9304.0"
            }
          ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x86-win'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x86-win.zip'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x86-win.zip
        artifactName: 'Windows32Signed'

  - job: SignWindows64Assemblies
    displayName: "Sign 64-bit Windows Assemblies"
    pool:
      vmImage: "windows-latest"
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: c6e283d3-5018-4982-b28f-8a88c50174e2
        pipeline: 7
        runVersion: specific
        runId: 47
        artifact: 'Windows64'
        path: $(Build.ArtifactStagingDirectory)
    - task: EsrpCodeSigning@1
      inputs:
        ConnectedServiceName: 'z3-esrp-signing'
        FolderPath: '$(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x64-win/bin'
        Pattern: 'Microsoft.Z3.dll,libz3.dll,libz3java.dll,z3.exe'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [
            {
              "keyCode": "CP-230012",
              "operationSetCode": "SigntoolSign",
              "parameters": [
                {
                  "parameterName": "OpusName",
                  "parameterValue": "Microsoft"
                },
                {
                  "parameterName": "OpusInfo",
                  "parameterValue": "http://www.microsoft.com"
                },
                {
                  "parameterName": "PageHash",
                  "parameterValue": "/NPH"
                },
                {
                  "parameterName": "FileDigest",
                  "parameterValue": "/fd sha256"
                },
                {
                  "parameterName": "TimeStamp",
                  "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                }
              ],
              "toolName": "signtool.exe",
              "toolVersion": "6.2.9304.0"
            }
          ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x64-win
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: $(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x64-win.zip
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/z3-$(ReleaseVersion)-x64-win.zip
        artifactName: 'Windows64Signed'

# Creates Z3 packages in various formats
- stage: Package
  jobs:

  - job: NuGetPackage
    displayName: "NuGet packaging"
    pool:
      vmImage: "windows-latest"
    steps:
    - powershell: write-host $(System.DefinitionId)
      displayName: "System.DefinitionId"
    - powershell: write-host $(Build.BuildId)
      displayName: "Build.BuildId"
    - powershell: write-host $(Build.BuildNumber)
      displayName: "Build.BuildNumber"
    - powershell: write-host $(Build.BuildUri)
      displayName: "Build.BuildUri"
    - powershell: write-host $(System.TeamProjectId)
      displayName: "System.TeamProjectId"
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'Windows64Signed'
        source: specific
        project: c6e283d3-5018-4982-b28f-8a88c50174e2
        pipeline: 7
        runVersion: specific
        runId: 61
        path: $(Agent.TempDirectory)\package
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'Ubuntu'
        source: specific
        project: c6e283d3-5018-4982-b28f-8a88c50174e2
        pipeline: 7
        runVersion: specific
        runId: 47
        path: $(Agent.TempDirectory)\package
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'Mac'
        source: specific
        project: c6e283d3-5018-4982-b28f-8a88c50174e2
        pipeline: 7
        runVersion: specific
        runId: 47
        path: $(Agent.TempDirectory)\package
    - task: PythonScript@0
      inputs:
        scriptSource: 'filepath'
        scriptPath: scripts\mk_nuget_task.py
        workingDirectory: $(Agent.TempDirectory)\package
        arguments:
          $(Agent.TempDirectory)\package
          $(ReleaseVersion)
          $(Build.Repository.Uri)
          $(Build.SourceBranchName)
          $(Build.SourceVersion)
          $(Build.SourcesDirectory)
    - task: NugetCommand@2
      inputs:
        command: pack
        basePath: $(Agent.TempDirectory)\package\out
        packagesToPack: '*.nuspec'
        packDestination: $(Build.ArtifactStagingDirectory)
    - powershell: get-childitem -recurse $(Agent.TempDirectory)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: 'NugetPackage'

#  - job: PythonPackage
#    condition: false
#    displayName: "Python packaging"
#    pool:
#      vmImage: "ubuntu-16.04"
#    steps:
#    - task: DownloadPipelineArtifact@0
#      inputs:
#        artifactName: 'Ubuntu'
#        targetPath: $(Agent.TempDirectory)
#    - task: DownloadPipelineArtifact@0
#      inputs:
#        artifactName: 'Manylinux'
#        targetPath: $(Agent.TempDirectory)
#    - script: cd $(Agent.TempDirectory); mkdir linux-bin; cd linux-bin; unzip ../*centos*.zip
#    - script: cd $(Agent.TempDirectory); mkdir win32-bin; cd win32-bin; unzip ../*x86-win*.zip
#    - script: cd $(Agent.TempDirectory); mkdir win64-bin; cd win64-bin; unzip ../*x64-win*.zip
#    - script: python -m pip install --user -U setuptools wheel
#    - script: cd src/api/python; python setup.py sdist
#   # take a look at this PREMIUM HACK I came up with to get around the fact that the azure variable syntax overloads the bash syntax for subshells
#    - script: cd src/api/python; echo $(Agent.TempDirectory)/linux-bin/* | xargs printf 'PACKAGE_FROM_RELEASE=%s\n' | xargs -I '{}' env '{}' python setup.py bdist_wheel
#    - script: cd src/api/python; echo $(Agent.TempDirectory)/win32-bin/* | xargs printf 'PACKAGE_FROM_RELEASE=%s\n' | xargs -I '{}' env '{}' python setup.py bdist_wheel
#    - script: cd src/api/python; echo $(Agent.TempDirectory)/win64-bin/* | xargs printf 'PACKAGE_FROM_RELEASE=%s\n' | xargs -I '{}' env '{}' python setup.py bdist_wheel
#    - task: PublishPipelineArtifact@0
#      inputs:
#        artifactName: 'Python packages'
#        targetPath: src/api/python/dist

# Uploads Z3 packages to various package stores
- stage: Publish
  jobs:

  - job: NuGetPublish
    displayName: "Publish to NuGet.org"
    steps:
    - powershell: write-host "publish nuget"
#
#  - job: GitHubPublish
#    displayName: "Publish to GitHub"
#    pool:
#      vmImage: "windows-latest"
#    steps:
#    - task: DownloadPipelineArtifact@0
#      inputs:
#        artifactName: 'Windows'
#        targetPath: tmp
#    - task: DownloadPipelineArtifact@0
#      inputs:
#        artifactName: 'Mac'
#        targetPath: tmp
#    - task: DownloadPipelineArtifact@0
#      inputs:
#        artifactName: 'Ubuntu'
#        targetPath: tmp
#    # TBD: this script should build a specific pre-specified tag
#    - task: GitHubRelease@0
#      inputs:
#        gitHubConnection: Z3GitHub
#        repositoryName: 'Z3Prover/z3'
#        action: 'create'
#        target: '$(Build.SourceVersion)'
#        tagSource: 'manual'
#        tag: 'z3-4.8.7'
#        title: 'z3-4.8.7'
#        releaseNotesSource: 'input'
#        releaseNotes: '4.8.7 release'
#        assets: 'tmp/*'
#        isDraft: true
#        isPreRelease: true
#
#  - job: PyPIPublish
#    displayName: "Publish to PyPI"
#    pool:
#      vmImage: "ubuntu-16.04"
#    steps:
#    - task: DownloadPipelineArtifact@0
#      inputs:
#        artifactName: 'Python packages'
#        targetPath: dist
#    - task: DownloadSecureFile@1
#      name: pypirc
#      inputs:
#        secureFile: 'pypirc'
#    - script: pip install --upgrade pip
#    - script: python -m pip install --user -U setuptools importlib_metadata wheel twine 
#    # Uncomment on release:
#    - script: python -m twine upload --config-file $(pypirc.secureFilePath) -r $(pypiReleaseServer) dist/*
#
# TBD: run regression tests on generated binaries.