name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ../
    - name: Run Make
      run: |
        cd build
        make -j4
        
