name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true     

jobs:               
  build:
    strategy:
      matrix:
        arch : [x86,x64,amd64_arm64]
        include:
         - arch : x86
         - arch : amd64_arm64
         - arch : x64
           cmd1 : 'julia -e "using Pkg; Pkg.add(PackageSpec(name=\"libcxxwrap_julia_jll\"))"'
           cmd2 : 'julia -e "using libcxxwrap_julia_jll; print(dirname(libcxxwrap_julia_jll.libcxxwrap_julia_path))" > tmp.env'
           cmd3 : 'set /P JlCxxDir=<tmp.env'
           test : 1
           bindings: -DJlCxx_DIR=%JlCxxDir%\..\lib